### 1) data preparing

In [4]:
import pandas as pd
import numpy as np

df_ktx = pd.DataFrame(
    data = {'경부선_KTX': [39060 , 39896 , 42005,  43621,  41702  ,41266  ,32427], 
            '호남선_KTX': [7313 , 6967 , 6873 , 6626 , 8675 , 10622,  9228] ,
            '경전선_KTX': [3627 , 4168  ,4088 , 4424,  4606 , 4984  ,5570] ,
            '전라선_KTX': [309 , 1771 , 1954 , 2244 , 3146,  3945,  5766] ,
            '동해선_KTX': [np.nan, np.nan,  np.nan , np.nan,  2395,  3786,  6667]} 
    ,
index = ['2011' , '2012',  '2013',  '2014' , '2015' , '2016'  ,'2017'])
df_ktx

경부선_KTX  호남선_KTX  경전선_KTX  전라선_KTX  동해선_KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

### 2) 추출

#### 2-1) 행 추출

행 시작위치~ 행 끝위치-1로 하면 된다

In [6]:
#첫 행 추출
df_ktx[1:2]

경부선_KTX  호남선_KTX  경전선_KTX  전라선_KTX  동해선_KTX
2012    39896     6967     4168     1771      NaN

In [9]:
#인덱스로 추출
#인덱스는 마지막-1이 아니라 해당 범위까지를 보여준다.
df_ktx.loc['2013':'2014'] 

경부선_KTX  호남선_KTX  경전선_KTX  전라선_KTX  동해선_KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN

In [11]:
#index의 location으로 볼 수 있다.
df_ktx.iloc[1:2]

경부선_KTX  호남선_KTX  경전선_KTX  전라선_KTX  동해선_KTX
2012    39896     6967     4168     1771      NaN

####  2-2) 열 추출

In [14]:
#첫번째열만 뽑기
df_ktx.iloc[:, 0:1]

경부선_KTX
2011    39060
2012    39896
2013    42005
2014    43621
2015    41702
2016    41266
2017    32427

In [15]:
#열 순서 바꿔서 뽑기
df_ktx.iloc[:, [3,2,1]]

전라선_KTX  경전선_KTX  호남선_KTX
2011      309     3627     7313
2012     1771     4168     6967
2013     1954     4088     6873
2014     2244     4424     6626
2015     3146     4606     8675
2016     3945     4984    10622
2017     5766     5570     9228

In [17]:
#2~4번째열 뽑기
df_ktx.iloc[:, 1:4]

호남선_KTX  경전선_KTX  전라선_KTX
2011     7313     3627      309
2012     6967     4168     1771
2013     6873     4088     1954
2014     6626     4424     2244
2015     8675     4606     3146
2016    10622     4984     3945
2017     9228     5570     5766

- 결론적으로 말하면, iloc 메서드가 R과 비슷하게 쓸 수 있게 해주는 방식이 아닌가 생각이 든다

#### 2-3) (열 이름을 알 경우) 열 추출

In [23]:
#기본 방식
df_ktx["경부선_KTX"]

2011    39060
2012    39896
2013    42005
2014    43621
2015    41702
2016    41266
2017    32427
Name: 경부선_KTX, dtype: int64

그러나 이상하게 뽑힌다. 방법이 없을까?

In [25]:
df_ktx.loc[:, "경부선_KTX"]

2011    39060
2012    39896
2013    42005
2014    43621
2015    41702
2016    41266
2017    32427
Name: 경부선_KTX, dtype: int64

하나만 뽑으면 Series로 뽑히는 듯 싶다.

In [27]:
pd.DataFrame(df_ktx["경부선_KTX"])
#이렇게 데이터 프레임으로 만들어주면 간단히 해결된다.

경부선_KTX
2011    39060
2012    39896
2013    42005
2014    43621
2015    41702
2016    41266
2017    32427

### 3) 필터걸기

#### 3-1) 행 필터

In [30]:
#열 하나만 걸고 필터걸기
df_ktx[df_ktx.경부선_KTX > 40000]

경부선_KTX  호남선_KTX  경전선_KTX  전라선_KTX  동해선_KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0

In [32]:
#복수조건 걸고 필터걸기
df_ktx[(df_ktx.경부선_KTX > 40000) & (df_ktx.호남선_KTX > 7000)]

경부선_KTX  호남선_KTX  경전선_KTX  전라선_KTX  동해선_KTX
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0

#### 3-2) 열 필터

In [35]:
df_KTX.filter(like = "경", axis = 1) #1은 열! 열일로 외우면 된다.

경부선_KTX  경전선_KTX
2011    39060     3627
2012    39896     4168
2013    42005     4088
2014    43621     4424
2015    41702     4606
2016    41266     4984
2017    32427     5570

### 4) 삭제

#### 4-1) 열 삭제

In [36]:
#한개 열 삭제
df_KTX.drop('경부선_KTX', axis = 1)

호남선_KTX  경전선_KTX  전라선_KTX  동해선_KTX
2011     7313     3627      309      NaN
2012     6967     4168     1771      NaN
2013     6873     4088     1954      NaN
2014     6626     4424     2244      NaN
2015     8675     4606     3146   2395.0
2016    10622     4984     3945   3786.0
2017     9228     5570     5766   6667.0

In [37]:
#두개 열 삭제
df_KTX.drop(['경부선_KTX', '경전선_KTX'], axis = 1)

호남선_KTX  전라선_KTX  동해선_KTX
2011     7313      309      NaN
2012     6967     1771      NaN
2013     6873     1954      NaN
2014     6626     2244      NaN
2015     8675     3146   2395.0
2016    10622     3945   3786.0
2017     9228     5766   6667.0

#### 4-2) 행 삭제

In [43]:
#index를 넣어서 삭제해주면 된다. 메서드처럼 여기도 1까지 모두 삭제됨
#index의 경우 0 = 2011, 1 = 2012 였음!
df_KTX.drop(df_KTX.index[[0,1]])

경부선_KTX  호남선_KTX  경전선_KTX  전라선_KTX  동해선_KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

### 5) 데이터 합치기 _ Numpy

In [8]:
import numpy as np
a = np.arange(3)
b = np.arange(4,7)

In [9]:
print(a)
print(b)

[0 1 2]
[4 5 6]


#### 5-1) 행 기준 병합

In [11]:
# (1) np.r_

np.r_[a,b] #()이 아니라 []를 사용한다.

array([0, 1, 2, 4, 5, 6])

In [13]:
# (2) np.hstack()

np.hstack([a,b])

array([0, 1, 2, 4, 5, 6])

In [14]:
# (3) np.concatenate((a,b), axis = 0)

np.concatenate((a,b), axis = 0)

array([0, 1, 2, 4, 5, 6])

#### 5-2) 열 기준 병합

In [17]:
# (1) np.c_

np.r_[[a], [b]] #[]으로 하나의 1-D 배열로 만들었다.

array([[0, 1, 2],
       [4, 5, 6]])

In [19]:
# (2) np.vstack()

np.vstack([a,b])

array([[0, 1, 2],
       [4, 5, 6]])

In [27]:
# (3) np.concatenate((a,b), axis = 1)

print(np.concatenate([[a,b]], axis = 1))

[[0 1 2]
 [4 5 6]]


#### 5-3) 두개의 1차원 row를 벡터화 해서 붙이기

In [28]:
np.c_[a,b]

array([[0, 4],
       [1, 5],
       [2, 6]])

In [30]:
np.column_stack([a,b])

array([[0, 4],
       [1, 5],
       [2, 6]])

### 5) 데이터 합치기 _ Pandas

In [54]:
import pandas as pd

a = pd.DataFrame(data = {
    'x1' : np.arange(1,5),
    'x2' : np.arange(4,8)
},
    index = [1,2,3,4])
b = pd.DataFrame(data = {
    'x2' : np.arange(11,15),
    'x3' : np.arange(41,45)
},
    index = [1,2,3,4])
print(a)
print(b)

   x1  x2
1   1   4
2   2   5
3   3   6
4   4   7
   x2  x3
1  11  41
2  12  42
3  13  43
4  14  44


#### 5-3) 행 기준 병합

- append 메서드 이용

In [61]:
a.append(b, ignore_index = True)

x1  x2
0   1   4
1   2   5
2   3   6
3   4   7
4  11  41
5  12  42
6  13  43
7  14  44

- pd.concat 이용

In [56]:
pd.concat([a,b], ignore_index = True) #요렇게 리스트 형식으로 넣어준다.

x1  x2    x3
0  1.0   4   NaN
1  2.0   5   NaN
2  3.0   6   NaN
3  4.0   7   NaN
4  NaN  11  41.0
5  NaN  12  42.0
6  NaN  13  43.0
7  NaN  14  44.0

- 그냥 밑으로 결합

In [105]:
a.columns, b.columns = ['x1', 'x2'], ['x1', 'x2']
a.append(b, ignore_index = True)

x1  x2
0   1   4
1   2   5
2   3   6
3   4   7
4  11  40
5  12  41
6  13  42
7  14  43

칼럼 명을 같게 해준 뒤 결합하면 그냥 붙이는 효과가 난다

#### 5-4) 열 기준 병합

- pd.concat(,,, axis = 1)

In [64]:
pd.concat([a,b], axis = 1)
#이렇게 한다음 칼럼명을 바꿔주든가 하면 될 것 같다.

x1  x2  x1  x2
1   1   4  11  41
2   2   5  12  42
3   3   6  13  43
4   4   7  14  44

- join 메서드

In [107]:
a.join(b, rsuffix = '_r')
#뭔가 suffix가 있는 join도 좋아보인다.
#여기도 on = 옵션이 있어서 key값을 설정할 수 있고, how 옵션으로 left와 right, outer과 inner를 조정할 수 있다.

x1  x2  x1_r  x2_r
0   1   4   NaN   NaN
1   2   5   NaN   NaN
2   3   6   NaN   NaN
3   4   7   NaN   NaN

#### 5-4-1) 열 index가 상이할 경우

- 열 index가 상이한 데이터 셋 구축

In [110]:
a2 = pd.DataFrame(data = {
    'x1' : np.arange(1,5),
    'x2' : np.arange(4,8)
},
    index = None)
b2 = pd.DataFrame(data = {
    'x1' : np.arange(11,15),
    'x2' : np.arange(40,44)
},
    index = ['a', 'b', 'c', 'd']) 

- join 메서드 이용

In [111]:
a2.join(b2, rsuffix = 'r')

x1  x2  x1r  x2r
0   1   4  NaN  NaN
1   2   5  NaN  NaN
2   3   6  NaN  NaN
3   4   7  NaN  NaN

In [114]:
a2.join(b2, how = 'right', rsuffix = 'r')

x1  x2  x1r  x2r
a NaN NaN   11   40
b NaN NaN   12   41
c NaN NaN   13   42
d NaN NaN   14   43

In [115]:
a.join(b, how = 'outer', rsuffix = 'r')

x1   x2   x1r   x2r
0  1.0  4.0   NaN   NaN
1  2.0  5.0   NaN   NaN
2  3.0  6.0   NaN   NaN
3  4.0  7.0   NaN   NaN
a  NaN  NaN  11.0  40.0
b  NaN  NaN  12.0  41.0
c  NaN  NaN  13.0  42.0
d  NaN  NaN  14.0  43.0

- pd.concat 메서드 이용

In [104]:
pd.concat([a2,b2],axis = 1, ignore_index = True)

0    1     2     3
0  1.0  4.0   NaN   NaN
1  2.0  5.0   NaN   NaN
2  3.0  6.0   NaN   NaN
3  4.0  7.0   NaN   NaN
a  NaN  NaN  11.0  40.0
b  NaN  NaN  12.0  41.0
c  NaN  NaN  13.0  42.0
d  NaN  NaN  14.0  43.0

열 기준으로 붙이기 위해서는 index가 같아야 하는 것 같다. 교수님이 R에서도 cbind는 조심해서 사용하라고 했던 게 여기서도 보여지는 것 같다.

- 칼럼 이름으로 먹이기

In [117]:
a['x3'] = b['x1']
a['x4'] = b['x2']
a

x1  x2  x3  x4
0   1   4 NaN NaN
1   2   5 NaN NaN
2   3   6 NaN NaN
3   4   7 NaN NaN

위 방법도 안된다... index는 파이썬에서 상당히 중요한 요소인 것 같다. 겸허히 index를 바꿔 결합해보자

In [120]:
b.index = [0,1,2,3]

a.drop(['x3', 'x4'], axis = 1, inplace=True)

a.join(b, how = 'outer', rsuffix = '_r')

x1  x2  x1_r  x2_r
0   1   4    11    40
1   2   5    12    41
2   3   6    13    42
3   4   7    14    43

결론적으로, join 메서드는 merge 메서드와 동일하게 on과 how를 쓸 수 있지만,index를 기준으로 join할 수 있고 suffix를 쓸 수 있다는 점에서 더 좋은 방식인 것 같다.