## reshape과 -1

reshape에 있어서 -1은 무엇인가? 이는 원래 배열을 reshape한 뒤 남은 차원이라고 한다. 무슨 의미인가?

In [6]:
import numpy as np

x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### row자리에 -1

In [3]:
x.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

--> 칼럼을 1로 가져간 뒤 남은 차원을 -1이 가져가게 된다

In [4]:
x.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

--> 이번엔 칼럼 개수를 2로 가져간 뒤 남은 차원을 -1이 가져가게 된다

In [4]:
x.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

--> 이번엔 칼럼 개수를 3으로 가져간 뒤 남은 차원(4)을 -1이 가져가게 된다

In [5]:
x.reshape(-1,5)

ValueError: cannot reshape array of size 12 into shape (5)

--> 5를 칼럼의 개수로 가져가게 되면, 나머지가 발생하기 때문에 reshape이 불가하다

### column 자리에 -1

In [7]:
x.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

--> row의 개수를 1개로 가지고 나머지 자리를 -1이 가져간다

In [8]:
x.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

--> row의 개수를 2로 가지고 나머지 차원을 -1이 가져간다

In [9]:
x.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

--> row의 개수를 3으로 가져가고 나머지 차원을 -1이 가져간다